### ISSUE TITLE
Could not establish connection error when trying to open dev space in new window

### ISSUE THREAD

**Issue by qmacro** [SAP/app-studio-toolkit#289]
Freshly installed saposs.app-studio-remote-access extension:

```text
Published 2023-07-19, 09:22:34
Last released 2023-10-01, 17:07:39
Last updated 2023-12-05, 15:38:39
Identifier saposs.app-studio-remote-access
```

on the latest version of VS Code on this macOS platform:

```text
Version: 1.84.2 (Universal)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:52:33.687Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.1.0
```

Authenticated, and I can see the dev space ("prep3") that I want to try to connect to:

![image](https://github.com/SAP/app-studio-toolkit/assets/73068/fa9b78d0-2b95-476b-8aee-023b1fc4167e)

I use the "Open in new window" icon, and in the new window, I get an error dialog box with "Could not establish connection to "xx72697etrial.us10cf.trial.applicationstudio.cloud.sap.ws-2jc78". Using the "Retry" option just brings the same error message.

If I hit "More Actions..." I can get to the log behind the dialog box, which includes this info (it's in the OUTPUT tab for a "Remote - SSH" connection):

```log
[15:51:06.374] Opening exec server for ssh-remote+xx72697etrial.us10cf.trial.applicationstudio.cloud.sap.ws-2jc78
[15:51:06.379] Initizing new exec server for ssh-remote+xx72697etrial.us10cf.trial.applicationstudio.cloud.sap.ws-2jc78
[15:51:06.386] Acquiring local install lock: /var/folders/61/c6jlmp4x12qf4hzj7flhkx1r0000gn/T/vscode-remote-ssh-7bfb94ff-install.lock
[15:51:06.388] Looking for existing server data file at /Users/I347491/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-7bfb94ff-1a5daa3a0231a0fbba4f14db7ec463cf99d7768e-0.107.1-es/data.json
[15:51:06.388] Using commit id "1a5daa3a0231a0fbba4f14db7ec463cf99d7768e" and quality "stable" for server
[15:51:06.389] Install and start server if needed
[15:51:06.395] askpass server listening on /var/folders/61/c6jlmp4x12qf4hzj7flhkx1r0000gn/T/vscode-ssh-askpass-0383cf58d266a3173b33feaeee6228f371f0d0d7.sock
[15:51:06.395] Spawning local server with {"serverId":2,"ipcHandlePath":"/var/folders/61/c6jlmp4x12qf4hzj7flhkx1r0000gn/T/vscode-ssh-askpass-f5cf5b3a3c85e96d504853cf0641841c98590bbe.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","62178","-o","ConnectTimeout=15","xx72697etrial.us10cf.trial.applicationstudio.cloud.sap.ws-2jc78","bash"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/I347491/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-7bfb94ff-1a5daa3a0231a0fbba4f14db7ec463cf99d7768e-0.107.1-es/data.json"}
[15:51:06.395] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.ZNtMUzRhvg/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/I347491/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/I347491/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/61/c6jlmp4x12qf4hzj7flhkx1r0000gn/T/vscode-ssh-askpass-0383cf58d266a3173b33feaeee6228f371f0d0d7.sock"}
[15:51:06.433] Spawned 35144
[15:51:06.501] > local-server-2> Running ssh connection command: "-v -T -D 62178 -o ConnectTimeout=15 xx72697etrial.us10cf.trial.applicationstudio.cloud.sap.ws-2jc78 bash"
[15:51:06.502] > local-server-2> Spawned ssh, pid=35147
[15:51:06.505] stderr> OpenSSH_9.4p1, LibreSSL 3.3.6
[15:51:06.508] stderr> /Users/I347491/.ssh/config line 20: Bad port '8022Host'.
[15:51:06.508] stderr> /Users/I347491/.ssh/config: terminating, 1 bad configuration options
[15:51:06.509] > local-server-2> ssh child died, shutting down
[15:51:06.514] Local server exit: 0
[15:51:06.514] Received install output: local-server-2> Running ssh connection command: "-v -T -D 62178 -o ConnectTimeout=15 xx72697etrial.us10cf.trial.applicationstudio.cloud.sap.ws-2jc78 bash"
local-server-2> Spawned ssh, pid=35147
OpenSSH_9.4p1, LibreSSL 3.3.6
/Users/I347491/.ssh/config line 20: Bad port '8022Host'.
/Users/I347491/.ssh/config: terminating, 1 bad configuration options
local-server-2> ssh child died, shutting down

[15:51:06.514] Failed to parse remote port from server output
[15:51:06.515] Exec server for ssh-remote+xx72697etrial.us10cf.trial.applicationstudio.cloud.sap.ws-2jc78 failed: Error
[15:51:06.515] Error opening exec server for ssh-remote+xx72697etrial.us10cf.trial.applicationstudio.cloud.sap.ws-2jc78: Error
```

So I notice this line:

```log
[15:51:06.508] stderr> /Users/I347491/.ssh/config line 20: Bad port '8022Host'.
```

and sure enough, an entry has been appended to my `~/.ssh/config` file, but the append process has not started on a new line:

```config
Host pixel
     Port 8022Host xx72697etrial.us10cf.trial.applicationstudio.cloud.sap.ws-2jc78
  HostName 127.0.0.1
  Port 33618
  IdentityFile /Users/I347491/.ssh/workspaces-ws-2jc78.us10.trial.applicationstudio.cloud.sap.key
  User user
  NoHostAuthenticationForLocalhost yes
Host xx72697etrial.us10cf.trial.applicationstudio.cloud.sap.ws-2jc78
  HostName 127.0.0.1
  Port 32352
  IdentityFile /Users/I347491/.ssh/workspaces-ws-2jc78.us10.trial.applicationstudio.cloud.sap.key
  User user
  NoHostAuthenticationForLocalhost yes
```

In other words, this already existed at the end of the `~/.ssh/config` file:

```config
Host pixel
     Port 8022
```

and it looks like there was no newline added before the append.

So I fix that, so it now looks like this:

```config
Host pixel
     Port 8022

Host 6d72697etrial.us10cf.trial.applicationstudio.cloud.sap.ws-2jc78
  HostName 127.0.0.1
  Port 33618
  ...
```

and try again. Still no joy, but at least a different error:

```log
[16:01:13.807] > local-server-1> Running ssh connection command: "-v -T -D 62394 -o ConnectTimeout=15 xx72697etrial.us10cf.trial.applicationstudio.cloud.sap.ws-2jc78 bash"
[16:01:13.808] > local-server-1> Spawned ssh, pid=35642
[16:01:13.811] stderr> OpenSSH_9.4p1, LibreSSL 3.3.6
[16:01:13.811] stderr> ssh: connect to host 127.0.0.1 port 32352: Connection refused
[16:01:13.812] > local-server-1> ssh child died, shutting down
[16:01:13.814] Local server exit: 0
[16:01:13.814] Received install output: local-server-1> Running ssh connection command: "-v -T -D 62394 -o ConnectTimeout=15 xx72697etrial.us10cf.trial.applicationstudio.cloud.sap.ws-2jc78 bash"
local-server-1> Spawned ssh, pid=35642
OpenSSH_9.4p1, LibreSSL 3.3.6
ssh: connect to host 127.0.0.1 port 32352: Connection refused
local-server-1> ssh child died, shutting down

[16:01:13.814] Failed to parse remote port from server output
[16:01:13.816] Resolver error: Error: 
	at g.Create (/Users/I347491/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:642703)
	at t.handleInstallOutput (/Users/I347491/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:640069)
	at e (/Users/I347491/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:700300)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async /Users/I347491/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:722169
	at async t.withShowDetailsEvent (/Users/I347491/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:725828)
	at async /Users/I347491/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:697005
	at async C (/Users/I347491/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:695056)
	at async t.resolveWithLocalServer (/Users/I347491/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:696545)
	at async I (/Users/I347491/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:719392)
	at async t.resolve (/Users/I347491/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:723199)
	at async /Users/I347491/.vscode/extensions/ms-vscode-remote.remote-ssh-0.107.1/out/extension.js:2:907003
[16:01:13.817] ------
```

Please help! Thanks.

**Comment by idoprz** [comment]
Hi DJ,
I guess the first issue is due to the ssh-config parser library we use. We will look at that, but I would like to address the second issue first.
Looking at the ssh-config file before you fixed the new line, I see you have two entries for the same dev-space.
Can you please delete both of them (keep new line at the end...) and try again?

**Comment by qmacro** [comment]
Hi @idoprz sorry I missed your reply! Let's close this, it's been a while, and now things seem to be working (and I cannot reproduce the error). Thanks.
